### ISSUE TITLE
strict is still running after Shiny app stopped

### ISSUE THREAD

**Issue by dracodoc** [hadley/strict#14] opened 2017-05-24 18:36 UTC
After error reported from `strict`, I terminated my Shiny app and start to fix the problems. Then I found there are still console output, and the source file cannot be saved, RStudio had problems connecting with the R session.

You can found below that there are some errors reported in console even I was just checking help documents.

```r
> shiny::runApp('shiny/app')
Loading required package: shiny
Loading required package: pacman

Listening on http://127.0.0.1:6016
sh: -c: line 0: syntax error near unexpected token `)'
sh: -c: line 0: `(<p>No data are available for download.</p>) > /var/folders/f3/6cdx4zf94qz95r6d89s_4xcsrcsjqm/T//RtmpWustTW/file6f1f331b7684'
Error in fread(res$res_cont, sep = ",", nrows = 5) : 
  file not found: /var/folders/f3/6cdx4zf94qz95r6d89s_4xcsrcsjqm/T//RtmpWustTW/file6f1f331b7684
Warning: Error in : [strict]
Multiple definitions found for `%>%`.
Please pick one:
 * stringr::%>%
 * DT::%>%
Stack trace (innermost first):
    87: <Anonymous>
    86: stop
    85: abort
    84: strict_abort
    83: <Anonymous>
    82: exprFunc [/Users/xhdong/Projects/ctmm-Shiny/shiny/app/server.R#295]
    81: widgetFunc
    80: func
    79: origRenderFunc
    78: renderFunc
    77: origRenderFunc
    76: output$individuals
     1: shiny::runApp

> ?`%>%`
Error: [strict]
Multiple definitions found for `plot`.
Please pick one:
 * ctmm::plot
 * graphics::plot
> ?plot
Error: [strict]
Multiple definitions found for `plot`.
Please pick one:
 * ctmm::plot
 * graphics::plot
Error: [strict]
Multiple definitions found for `plot`.
Please pick one:
 * ctmm::plot
 * graphics::plot
Error: [strict]
Multiple definitions found for `plot`.
Please pick one:
 * ctmm::plot
 * graphics::plot
Error: [strict]
Multiple definitions found for `plot`.
Please pick one:
 * ctmm::plot
 * graphics::plot
Error: Unable to establish connection with R session
Error: Unable to establish connection with R session
```

**Comment by hadley** [comment] 2017-05-24 18:45
This is basically a duplicate of #5

**Closed by hadley** 2017-05-24 18:45 UTC
